INSERT INTO [dbo.pouring]
           (LineCode
           ,SessionID
           ,FM
           ,ProductCode
           ,StartTime
           ,FinishTime
           ,Temperature
           ,PinSample
           ,PanjangChill
           ,Mold
           ,TotalMold
           ,MoldNG
           ,PourNG
           ,Empty
           ,OperatorID
           ,FaddingTime
           ,C
           ,Si
           ,Mn
           ,Ti
           ,Ni
           ,Al
           ,V
           ,Zn
           ,Sb
           ,Mo
           ,S
           ,Cu
           ,Sn
           ,Mg
           ,Cr
           ,P
           ,Fe1
           ,Fe2
           ,Inspection
           ,StopLineID
           ,StopTimeStart
           ,StopTimeFinish
           ,StopDuration
           ,RecordTime
           ,AssetID)
     VALUES